---
- name: "Deploying Infarastructure & setting up a web server in an EC2"
  hosts: all
  ignore_unreachable: true
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  
  roles:
    - setup